### ISSUE TITLE
update libsodium 1.0.11 -> 1.0.13

### ISSUE THREAD

**Issue by JBlaschke** [cryptosphere/rbnacl-libsodium#13]
libsodium 1.0.11 does not compile on Uberspace servers (CentOS 6, gcc 5), going to libsodium 1.0.13 (current release) does compile (I tested it with toast).

Is it possible to upgrade the libsodium backend to 1.0.13?

**Comment by jhellenthal** [comment]
Having the same issue here.

**Comment by tarcieri** [comment]
Updated to libsodium 1.0.13 in eb88b3c43f805ea6ce51bad55e4f3c6a38ab4c21
