### ISSUE TITLE
Error while installing on Termux

### ISSUE THREAD

**Issue by K4L13CL1P53** [cryptosphere/rbnacl-libsodium#14]
Termux is a terminal emulator for  Android. While installing the gem, I encountered this problem.
![20170812_201904](https://user-images.githubusercontent.com/30959456/29242830-9e9bf494-7f9c-11e7-870b-7f0d352a832d.png)

**Comment by tarcieri** [comment]
Not a lot to go on here... `./configure` isn't being generated. Perhaps you don't have autoconf installed?

**Comment by Auxilus** [comment]
I got the same error, I have `autoconf` installed.

**Comment by jedisct1** [comment]
https://github.com/jedisct1/libsodium/issues/445#issuecomment-261803641

**Comment by tarcieri** [comment]
Please discuss this on the upstream issue

**Comment by Auxilus** [comment]
I installed the package but i cant install gem..
