### ISSUE TITLE
[Mac][AESNI] rbnacl-libsodium 1.0.13 compile problems

### ISSUE THREAD

**Issue by jhellenthal** [cryptosphere/rbnacl-libsodium#15]
Please see the attached make output. Seem to have some missing symbols here and not quite sure which direction to go with this.

If further information is needed or extended patch testing let me know.

[gem_make.txt](https://github.com/cryptosphere/rbnacl-libsodium/files/1247833/gem_make.txt)

**Comment by tarcieri** [comment]
You appear to be on an CPU architecture that does not support CLMUL.

Please file a bug upstream with libsodium:

https://github.com/jedisct1/libsodium

**Comment by jhellenthal** [comment]
Thanks
