### ISSUE TITLE
corrupted double linked list 

### ISSUE THREAD

**Issue by dbuker** [cryptosphere/rbnacl-libsodium#5]
When attempting to install rbnacl-libsodium I get the following.

daniel@daniel-Latitude-D630:~/src/libsodium-1.0.1$ gem install rbnacl-libsodium
Building native extensions.  This could take a while...
*** Error in `/usr/bin/ld': corrupted double-linked list: 0x09abe5b0 ***

It then proceeds to behave as if the gem installed. However, when I "require 'rbnacl/libsodium'" I get a whole slew of problems:
daniel@daniel-Latitude-D630:~/Sandbox$ ruby Encrypt.rb
/home/daniel/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rbnacl/libsodium (LoadError)
	from /home/daniel/.rubies/ruby-2.1.3/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from Encrypt.rb:4:in `<main>'

If it's any help, I'm using Ruby version 2.1.3 and I'm attempting to get this to work on lubuntu 14.04

**Comment by tarcieri** [comment]
This sounds like a bug in your version of ld
